apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: rainmaker
      defaultBucket: default
      tlsSkipVerify: true
    secureJsonData:
      token: xQ9iJbCXc-_YluN28wFfd_FZmasUfDU4xRQTd4cNY3g6C4cyXXhzhZybKnYe-Dor8X2GkNHrQ1FlKWfK9g562Q==
    isDefault: true
    editable: true
